import subprocess
from typing import List, Optional

from github import Github, GithubException

from bot.scanner import Finding

BOT_COMMENT_MARKER = "## Bot Review:"


def _get_client(token: str) -> Github:
    return Github(token)


def post_pr_comment(token: str, repo_name: str, pr_number: int, comment: str) -> None:
    g = _get_client(token)
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    # Replace existing bot comment rather than stacking new ones
    try:
        bot_login = g.get_user().login
        for existing in pr.get_issue_comments():
            if existing.user.login == bot_login and BOT_COMMENT_MARKER in existing.body:
                existing.edit(comment)
                return
    except GithubException:
        pass  # Can't list comments — fall through to create

    pr.create_issue_comment(comment)


def commit_auto_fixes(branch: str) -> None:
    """Stage and commit auto-fix changes back to the PR branch."""
    subprocess.run(["git", "config", "user.email", "devsecops-bot@noreply.github.com"], check=True)
    subprocess.run(["git", "config", "user.name", "DevSecOps Bot"], check=True)
    subprocess.run(["git", "add", "-A"], check=True)

    status = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
    if status.stdout.strip():
        subprocess.run([
            "git", "commit", "-m",
            "style: auto-fix formatting and unused imports [skip ci]",
        ], check=True)
        subprocess.run(["git", "push", "origin", f"HEAD:{branch}"], check=True)


def create_cve_fix_pr(token: str, repo_name: str, cve_findings: List[Finding]) -> Optional[str]:
    """Open a PR that annotates requirements.txt with CVE information for human review."""
    if not cve_findings:
        return None

    g = _get_client(token)
    repo = g.get_repo(repo_name)

    try:
        req_file = repo.get_contents("requirements.txt")
    except GithubException:
        return None

    original_content = req_file.decoded_content.decode("utf-8")

    # Build updated content: prepend a CVE advisory block as comments
    cve_block_lines = [
        "# ============================================================",
        "# CVE ADVISORY — auto-generated by DevSecOps Bot nightly scan",
        "# Review each item and pin to a patched version.",
        "# ============================================================",
    ]
    for f in cve_findings:
        cve_block_lines.append(f"# [{f.rule_id}] {f.title}")
        if f.message:
            cve_block_lines.append(f"#   {f.message[:120]}")
    cve_block_lines.append("# ============================================================")
    cve_block_lines.append("")

    new_content = "\n".join(cve_block_lines) + original_content

    default_branch = repo.default_branch
    base_sha = repo.get_branch(default_branch).commit.sha
    branch_name = f"fix/cve-deps-{base_sha[:7]}"

    # Create branch (skip if already exists)
    try:
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
    except GithubException as exc:
        if exc.status == 422:
            return None
        raise

    repo.update_file(
        path="requirements.txt",
        message=f"fix: annotate {len(cve_findings)} CVE(s) in requirements.txt",
        content=new_content,
        sha=req_file.sha,
        branch=branch_name,
    )

    vuln_list = "\n".join(
        f"- **{f.rule_id}**: {f.title}" for f in cve_findings
    )
    pr = repo.create_pull(
        title=f"fix: address {len(cve_findings)} CVE(s) in dependencies",
        body=(
            "## Automated CVE Report\n\n"
            "This PR was opened by the **DevSecOps Bot** nightly CVE scan.\n\n"
            "### Vulnerabilities Found\n\n"
            f"{vuln_list}\n\n"
            "> **Action required:** Update each listed package to a safe version "
            "and remove the advisory comments before merging."
        ),
        head=branch_name,
        base=default_branch,
    )
    return pr.html_url
